# Dockerfile for building "compat" variant of Wasm Image Specification.
# https://github.com/solo-io/wasm/blob/master/spec/spec-compat.md
FROM scratch

ARG WASM_PLUGIN_NAME

COPY $WASM_PLUGIN_NAME.wasm ./plugin.wasm